import AnimatedText from '@/components/AnimatedText'
import TransitionEffect from '@/components/TransitionEffect'
import React, { useState } from "react";
import { motion } from "framer-motion";
// import emailjs from "@/emailjs/browser";
import emailjs from 'emailjs-com';
import Head from 'next/head'
import Layout from '@/components/Layout.js';
import phone from '../../public/phone.png'
import ct from '../../public/images/ct.png'
import Image from 'next/image.js';
import ContactMe from '@/components/ContactMe';

const contact = () => {
  return (
    <>
      <Head>
        <title>SPV || contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <ContactMe />
    </>
  )
}

export default contact

{/* <div className='text-dark dark:text-light min-h-screen w-full bgc'>
        <TransitionEffect />
        contact
    </div> */}